DROP TABLE IF EXISTS siep.informations_batiments;
CREATE TABLE IF NOT EXISTS siep.informations_batiments (
    id BIGSERIAL PRIMARY KEY,
    code_batiment TEXT,
    code_batiment_rt BIGINT,
    nom_batiment TEXT,
    code_site TEXT,
    nom_site TEXT,
    typologie_batiment TEXT,
    typologie_detaillee TEXT,
    adresse TEXT,
    code_postal INT,
    ville TEXT,
    departement TEXT,
    region TEXT,
    surface_occupee_dans_batiment DOUBLE PRECISION,
    surface_totale_du_batiment DOUBLE PRECISION,
    id_gestionnaire BIGINT,
    gestionnaire_batiment TEXT,
    ministere_ou_ep TEXT,
    id_du_ministere INT,
    ministere TEXT,
    direction_occupante TEXT,
    multi_occupation BOOLEAN,
    etat_batiment TEXT,
    nb_total_postes_de_travail BIGINT,
    effectif_total_batiment BIGINT,
    date_sortie_du_batiment DATE,
    date_sortie_du_site DATE,
    date_de_construction TEXT,
    date_derniere_renovation DATE,
    date_export_rt DATE,
    batiment_soumis_deet BOOLEAN,
    efa TEXT,
    annee_reference TEXT,
    perimetre TEXT
);
