DROP TABLE IF EXISTS siep.bien_eligibilite_fcu CASCADE;
CREATE TABLE IF NOT EXISTS siep.bien_eligibilite_fcu (
    id_row bigint GENERATED ALWAYS AS IDENTITY,
    code_bat_ter BIGINT NOT NULL,
    is_eligible BOOLEAN,
    distance INT,
    distance_rattachement TEXT,
    in_pdp BOOLEAN,
    pdp TEXT,
    -- is_based_on_iris BOOLEAN,
    futur_network BOOLEAN,
    rcu_etat TEXT,
    id_fcu TEXT,
    name TEXT,
    gestionnaire_fcu TEXT,
    -- rate_enrr DOUBLE PRECISION,
    taux_enrr_rcu DOUBLE PRECISION,
    rate_co2 DOUBLE PRECISION,
    contenu_rcu_gco2 DOUBLE PRECISION,
    api_status TEXT,
    api_status_code INT,
    api_raison TEXT,
    import_timestamp TIMESTAMP NOT NULL,
    snapshot_id UUID NOT NULL,
    snapshot_id_parent UUID NULL,
    PRIMARY KEY (id_row, import_timestamp),
    UNIQUE (import_timestamp, code_bat_ter),
    FOREIGN KEY(code_bat_ter, import_timestamp_oad, import_timestamp) REFERENCES siep.bien(code_bat_ter, import_timestamp, import_timestamp)
)PARTITION BY RANGE (import_timestamp);
