DROP TABLE IF EXISTS siep.ademe_declaration_detail CASCADE;
CREATE TABLE IF NOT EXISTS siep.ademe_declaration_detail (
    id_row bigint GENERATED ALWAYS AS IDENTITY,
    id_consommation INTEGER,
    ref_operat_efa TEXT,
    annee_declaree TEXT,
    date_debut_conso_reference DATE,
    categorie_activite_principale TEXT,
    vehi_elec_nb_bornes INTEGER,
    vehi_elec_conso_avc_irve_kwh DOUBLE PRECISION,
    conso_indi_hors_irve_kwh DOUBLE PRECISION,
    conso_indi_gaz_nat_reseaux_kwh DOUBLE PRECISION,
    conso_indi_gaz_nat_liquefie_kg DOUBLE PRECISION,
    conso_indi_gaz_propane_kg DOUBLE PRECISION,
    conso_indi_gaz_propane_m3 DOUBLE PRECISION,
    conso_indi_gaz_butane_kg DOUBLE PRECISION,
    conso_indi_gaz_butane_m3 DOUBLE PRECISION,
    conso_indi_fioul_domesti_litre DOUBLE PRECISION,
    conso_indi_charbon_agglo_briq_kg DOUBLE PRECISION,
    conso_indi_houille_kg DOUBLE PRECISION,
    conso_indi_bois_plaq_industrie_kg DOUBLE PRECISION,
    conso_indi_bois_plaq_forest_kg DOUBLE PRECISION,
    conso_indi_bois_gran_briq_kg DOUBLE PRECISION,
    conso_indi_bois_buches_stere DOUBLE PRECISION,
    conso_indi_reseau_chaleur_kwh DOUBLE PRECISION,
    conso_indi_reseau_froid_kwh DOUBLE PRECISION,
    conso_indi_gazole_non_routier_litre DOUBLE PRECISION,
    conso_rep_hors_irve_kwh DOUBLE PRECISION,
    conso_rep_gaz_nat_reseaux_kwh DOUBLE PRECISION,
    conso_rep_gaz_nat_liquefie_kg DOUBLE PRECISION,
    conso_rep_gaz_propane_kg DOUBLE PRECISION,
    conso_rep_gaz_propane_m3 DOUBLE PRECISION,
    conso_rep_gaz_butane_kg DOUBLE PRECISION,
    conso_rep_gaz_butane_m3 DOUBLE PRECISION,
    conso_rep_fioul_domesti_litre DOUBLE PRECISION,
    conso_rep_charbon_agglo_briq_kg DOUBLE PRECISION,
    conso_rep_houille_kg DOUBLE PRECISION,
    conso_rep_bois_plaq_industrie_kg DOUBLE PRECISION,
    conso_rep_bois_plaq_forest_kg DOUBLE PRECISION,
    conso_rep_bois_gran_briq_kg DOUBLE PRECISION,
    conso_rep_bois_buches_stere DOUBLE PRECISION,
    conso_rep_reseau_chaleur_kwh DOUBLE PRECISION,
    conso_rep_reseau_froid_kwh DOUBLE PRECISION,
    conso_rep_gazole_non_routier_litre DOUBLE PRECISION,
    conso_com_hors_irve_kwh DOUBLE PRECISION,
    conso_com_gaz_nat_reseaux_kwh DOUBLE PRECISION,
    conso_com_gaz_nat_liquefie_kg DOUBLE PRECISION,
    conso_com_gaz_propane_kg DOUBLE PRECISION,
    conso_com_gaz_propane_m3 DOUBLE PRECISION,
    conso_com_gaz_butane_kg DOUBLE PRECISION,
    conso_com_gaz_butane_m3 DOUBLE PRECISION,
    conso_com_fioul_domesti_litre DOUBLE PRECISION,
    conso_com_charbon_agglo_briq_kg DOUBLE PRECISION,
    conso_com_houille_kg DOUBLE PRECISION,
    conso_com_bois_plaq_industrie_kg DOUBLE PRECISION,
    conso_com_bois_plaq_forest_kg DOUBLE PRECISION,
    conso_com_bois_gran_briq_kg DOUBLE PRECISION,
    conso_com_bois_buches_stere DOUBLE PRECISION,
    conso_com_reseau_chaleur_kwh DOUBLE PRECISION,
    conso_com_reseau_froid_kwh DOUBLE PRECISION,
    conso_com_gazole_non_routier_litre DOUBLE PRECISION,
    station_meteo_efa DOUBLE PRECISION,
    chauffage_conso_elec_kwh DOUBLE PRECISION,
    chauffage_conso_gaz_nat_reseaux_kwh DOUBLE PRECISION,
    chauffage_conso_gaz_nat_liquefie_kg DOUBLE PRECISION,
    chauffage_conso_gaz_propane_kg DOUBLE PRECISION,
    chauffage_conso_gaz_propane_m3 DOUBLE PRECISION,
    chauffage_conso_gaz_butane_kg DOUBLE PRECISION,
    chauffage_conso_gaz_butane_m3 DOUBLE PRECISION,
    chauffage_conso_fioul_domesti_litre DOUBLE PRECISION,
    chauffage_conso_charbon_agglo_briq_kg DOUBLE PRECISION,
    chauffage_conso_houille_kg DOUBLE PRECISION,
    chauffage_conso_bois_plaq_industrie_kg DOUBLE PRECISION,
    chauffage_conso_bois_plaq_forest_kg DOUBLE PRECISION,
    chauffage_conso_bois_gran_briq_kg DOUBLE PRECISION,
    chauffage_conso_bois_buches_stere DOUBLE PRECISION,
    chauffage_conso_reseau_chaleur_kwh DOUBLE PRECISION,
    chauffage_conso_reseau_froid_kwh DOUBLE PRECISION,
    chauffage_conso_gazole_non_routier_litre DOUBLE PRECISION,
    refroidissement_conso_elec_kwh DOUBLE PRECISION,
    refroidissement_conso_gaz_nat_reseaux_kwh DOUBLE PRECISION,
    refroidissement_conso_gaz_nat_liquefie_kg DOUBLE PRECISION,
    refroidissement_conso_gaz_propane_kg DOUBLE PRECISION,
    refroidissement_conso_gaz_propane_m3 DOUBLE PRECISION,
    refroidissement_conso_gaz_butane_kg DOUBLE PRECISION,
    refroidissement_conso_gaz_butane_m3 DOUBLE PRECISION,
    refroidissement_conso_fioul_domesti_litre DOUBLE PRECISION,
    refroidissement_conso_charbon_agglo_briq_kg DOUBLE PRECISION,
    refroidissement_conso_houille_kg DOUBLE PRECISION,
    refroidissement_conso_bois_plaq_industrie_kg DOUBLE PRECISION,
    refroidissement_conso_bois_plaq_forest_kg DOUBLE PRECISION,
    refroidissement_conso_bois_gran_briq_kg DOUBLE PRECISION,
    refroidissement_conso_bois_buches_stere DOUBLE PRECISION,
    refroidissement_conso_reseau_chaleur_kwh DOUBLE PRECISION,
    refroidissement_conso_reseau_froid_kwh DOUBLE PRECISION,
    refroidissement_conso_gazole_non_routier_litre DOUBLE PRECISION,
    froid_logist_hauteur_refroidie DOUBLE PRECISION,
    froid_logist_conso_elec_kwh DOUBLE PRECISION,
    froid_logist_conso_gaz_nat_reseaux_kwh DOUBLE PRECISION,
    froid_logist_conso_gaz_nat_liquefie_kg DOUBLE PRECISION,
    froid_logist_conso_gaz_propane_kg DOUBLE PRECISION,
    froid_logist_conso_gaz_propane_m3 DOUBLE PRECISION,
    froid_logist_conso_gaz_butane_kg DOUBLE PRECISION,
    froid_logist_conso_gaz_butane_m3 DOUBLE PRECISION,
    froid_logist_conso_fioul_domesti_litre DOUBLE PRECISION,
    froid_logist_conso_charbon_agglo_briq_kg DOUBLE PRECISION,
    froid_logist_conso_houille_kg DOUBLE PRECISION,
    froid_logist_conso_bois_plaq_industrie_kg DOUBLE PRECISION,
    froid_logist_conso_bois_plaq_forest_kg DOUBLE PRECISION,
    froid_logist_conso_bois_gran_briq_kg DOUBLE PRECISION,
    froid_logist_conso_bois_buches_stere DOUBLE PRECISION,
    froid_logist_conso_reseau_chaleur_kwh DOUBLE PRECISION,
    froid_logist_conso_reseau_froid_kwh DOUBLE PRECISION,
    froid_logist_conso_gazole_non_routier_litre DOUBLE PRECISION,
    froid_com_conso_elec_kwh DOUBLE PRECISION,
    froid_com_conso_gaz_nat_reseaux_kwh DOUBLE PRECISION,
    froid_com_conso_gaz_nat_liquefie_kg DOUBLE PRECISION,
    froid_com_conso_gaz_propane_kg DOUBLE PRECISION,
    froid_com_conso_gaz_propane_m3 DOUBLE PRECISION,
    froid_com_conso_gaz_butane_kg DOUBLE PRECISION,
    froid_com_conso_gaz_butane_m3 DOUBLE PRECISION,
    froid_com_conso_fioul_domesti_litre DOUBLE PRECISION,
    froid_com_conso_charbon_agglo_briq_kg DOUBLE PRECISION,
    froid_com_conso_houille_kg DOUBLE PRECISION,
    froid_com_conso_bois_plaq_industrie_kg DOUBLE PRECISION,
    froid_com_conso_bois_plaq_forest_kg DOUBLE PRECISION,
    froid_com_conso_bois_gran_briq_kg DOUBLE PRECISION,
    froid_com_conso_bois_buches_stere DOUBLE PRECISION,
    froid_com_conso_reseau_chaleur_kwh DOUBLE PRECISION,
    froid_com_conso_reseau_froid_kwh DOUBLE PRECISION,
    froid_com_conso_gazole_non_routier_litre DOUBLE PRECISION,
    conservation_doc_conso_elec_kwh DOUBLE PRECISION,
    conservation_doc_conso_gaz_nat_reseaux_kwh DOUBLE PRECISION,
    conservation_doc_conso_gaz_nat_liquefie_kg DOUBLE PRECISION,
    conservation_doc_conso_gaz_propane_kg DOUBLE PRECISION,
    conservation_doc_conso_gaz_propane_m3 DOUBLE PRECISION,
    conservation_doc_conso_gaz_butane_kg DOUBLE PRECISION,
    conservation_doc_conso_gaz_butane_m3 DOUBLE PRECISION,
    conservation_doc_conso_fioul_domesti_litre DOUBLE PRECISION,
    conservation_doc_conso_charbon_agglo_briq_kg DOUBLE PRECISION,
    conservation_doc_conso_houille_kg DOUBLE PRECISION,
    conservation_doc_conso_bois_plaq_industrie_kg DOUBLE PRECISION,
    conservation_doc_conso_bois_plaq_forest_kg DOUBLE PRECISION,
    conservation_doc_conso_bois_gran_briq_kg DOUBLE PRECISION,
    conservation_doc_conso_bois_buches_stere DOUBLE PRECISION,
    conservation_doc_conso_reseau_chaleur_kwh DOUBLE PRECISION,
    conservation_doc_conso_reseau_froid_kwh DOUBLE PRECISION,
    conservation_doc_conso_gazole_non_routier_litre DOUBLE PRECISION,
    import_timestamp TIMESTAMP NOT NULL,
    import_date DATE NOT NULL,
	snapshot_id TEXT,
    PRIMARY KEY (id_row, import_timestamp),
    FOREIGN KEY (id_consommation, import_timestamp) REFERENCES siep.ademe_declaration(id_consommation, import_timestamp)
) PARTITION BY RANGE (import_timestamp);

DROP TABLE IF EXISTS siep.ademe_declaration_activite CASCADE;
CREATE TABLE IF NOT EXISTS siep.ademe_declaration_activite (
    id_row bigint GENERATED ALWAYS AS IDENTITY,
    id_consommation INTEGER,
    sous_categorie_activite TEXT,
    surface_plancher_m2 DOUBLE PRECISION,
    date_debut_activite DATE,
    date_fin_activite DATE,
    chauffage TEXT,
    refroidissement TEXT,
    logistique_de_froid TEXT,
    froid_commercial TEXT,
    conservation_doc_collections TEXT,
    import_timestamp TIMESTAMP NOT NULL,
    import_date DATE NOT NULL,
	snapshot_id TEXT,
    PRIMARY KEY (id_row, import_timestamp),
    FOREIGN KEY (id_consommation, import_timestamp) REFERENCES siep.ademe_declaration(id_consommation, import_timestamp)
) PARTITION BY RANGE (import_timestamp);


DROP TABLE IF EXISTS siep.ademe_declaration_indicateur CASCADE;
CREATE TABLE IF NOT EXISTS siep.ademe_declaration_indicateur (
    id_row bigint GENERATED ALWAYS AS IDENTITY,
    id_consommation INTEGER,
    numero_indicateur TEXT,
    nom_indicateur TEXT,
    numero_valeur_indicateur TEXT,
    valeur_indicateur DOUBLE PRECISION,
    import_timestamp TIMESTAMP NOT NULL,
    import_date DATE NOT NULL,
	snapshot_id TEXT,
    PRIMARY KEY (id_row, import_timestamp),
    FOREIGN KEY (id_consommation, import_timestamp) REFERENCES siep.ademe_declaration(id_consommation, import_timestamp)
) PARTITION BY RANGE (import_timestamp);
